### ISSUE TITLE
Curly brackets('{', '}') in atttributes names are not saved to file correctly. 

### ISSUE THREAD

**Issue by kamil-jurek** [KayJay624/Haquna#1]
Curly brackets('{', '}') in atttributes names are not saved to file correctly.

**Comment by KayJay624** [comment]
Probably, when saving attribute to file, there is a need to add apostrophes (') around atrribute name when name consists of characters other than letters. ToDo

**Comment by KayJay624** [comment]
Resolved by adding a method that checks weather attribute name, attribute description contains of chars other than letters.
